### ISSUE TITLE
./xmpp.sh: 384: local: cat --ssl suchat.org 5222: bad variable name

### ISSUE THREAD

**Issue by ManuVidal** [close2/shell-xmpp-client#4]
Hi!

I have this problem

./xmpp.sh --connect --jid myaccount@suchat.org --pass my password
./xmpp.sh: 384: local: cat --ssl suchat.org 5222: bad variable name

I'm using ubuntu 14.04 LTS

Note. With other clients like mcabber, I have no problems with that account

**Comment by ManuVidal** [comment]
Sorry. With #!/bin/bash instead of #!/bin/sh, it's ok but I've other error: 
"Ncat: Input/output error". 

I'm going to search about it...

**Comment by close2** [comment]
Hi
were you able to find out why you got the Ncat error?

**Comment by ManuVidal** [comment]
Hi! sorry by late response

I was insert in line 29 the option "--sctp", it looks like this:
ncat="ncat --sctp --ssl suchat.org 5222",

and now I have other error:
"Ncat: Connection timed out."

I think that this can by the server... I think that perhaps I don't understand xmpp protocol options with the server very well, cos with other clients like kopete, the account works fine!

Thanks very much
